// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PTD_KTRA.Data;

#nullable disable

namespace PTD_Ktra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250525045947_Create_table_Test")]
    partial class Create_table_Test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("PTD_KTRA.Models.Test", b =>
                {
                    b.Property<string>("HoTen")
                        .HasColumnType("TEXT");

                    b.Property<int>("Masv")
                        .HasColumnType("INTEGER");

                    b.HasKey("HoTen");

                    b.ToTable("Test");
                });
#pragma warning restore 612, 618
        }
    }
}
